#!/bin/sh
#
# Copyright 1999-2000 Igor Chudov
#
# This file is part of STUMP.
# 
# STUMP is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# STUMP is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with STUMP.  If not, see <https://www.gnu.org/licenses/>.
#
# This script sends an email to a group of people listed in
# env var RECIPIENTS (we create this var here from etc/moderators)
#
# It is used to maintain the little internal mailing list for all
# human moderators of your newsgroup.
#

FILTER="NO_$2_LIST";

RECIPIENTS="$(grep -v "$FILTER" "$MNG_ROOT"/etc/moderators \
             | grep -v '^#'                                \
             | awk '{print $1;}'                           \
             | tr '\n' ',' )"

(
     formail                                                            \
       -I "To: devnull@algebra.com"					\
       -I "From " -I "Cc:"                                              \
       -I "X-Loop: $BOARD"                            			\
       -I "X-Mailing-List: $BOARD ($NEWSGROUP Moderators)" 		\
       -I "Reply-To: $1"                          	                \
       -I "Resent-To:"							\
       -I "X-Maintainer: $ADMIN"    					\
       -I "Errors-To: $ADMIN"
     cat "$MNG_ROOT"/etc/mods.sig
) | sed 's/^\.$/\.\./' | sendmail "$RECIPIENTS"
