#!/usr/bin/env perl
#
# Copyright 1999-2000 Igor Chudov
#
# This file is part of STUMP.
# 
# STUMP is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# STUMP is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with STUMP.  If not, see <https://www.gnu.org/licenses/>.

$DataDir = $ENV{'MNG_ROOT'} . "/data";
$NewsgroupsDBFile = "$DataDir/Newsgroups";

# Open message-ID database
dbmopen( %NewsgroupsDB, "$NewsgroupsDBFile", 0644 );


while( <> ) {
  ($group, $q1, $q2, $flag) = split;
  $NewsgroupsDB{$group} = $flag;
}

print "test: $NewsgroupsDB{'soc.culture.russian'}.\n"
