#!/bin/sh
#
# Copyright 1999-2000 Igor Chudov
#
# This file is part of STUMP.
# 
# STUMP is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# STUMP is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with STUMP.  If not, see <https://www.gnu.org/licenses/>.

DATE="`date +%y%m%d`"

ArchFile() {
  FILE=$1
  DEST=$MNG_ROOT/archive/old/$FILE.$DATE
  mv $MNG_ROOT/archive/$FILE $DEST
  gzip -9 $MNG_ROOT/archive/old/$FILE.$DATE
  chmod 644 $DEST.gz
  ln -fs $DEST.gz $MNG_ROOT/archive/old/$FILE.current
}

ArchFile approved
ArchFile rejected
ArchFile incoming

echo New copy of archive has been created. Please update your home page \
  | mail $ADMIN
