#!/usr/bin/env perl
#
# Copyright 1999-2000 Igor Chudov
#
# This file is part of STUMP.
# 
# STUMP is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# STUMP is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with STUMP.  If not, see <https://www.gnu.org/licenses/>.

$isEncoded = 0;
$FullHeaders = "";
$DecodedHeaders = "";
$switch = "";

while(<>) {
  chop;

  last if( /^$/ );

  $FullHeaders .= "$_\n";

  if( /^Content-Transfer-Encoding: BASE64/i ) {

    $isEncoded = 1;
    $switch = "-b"; # base64 - default

  } elsif( /^Content-Transfer-Encoding: quoted-printable/i ) {

    $isEncoded = 1;
    $switch = "-q"; # quoted-printable

  } elsif( ! /^Mime-Version: /i && ! /Content-Type: /i ) {
    $DecodedHeaders .= "$_\n";
  }
}

# body

if( !$isEncoded ) {
  print $FullHeaders . "\n";
  while( <> ) {
    print;
  }
  exit 0;
}

print $DecodedHeaders . "\n";

if( $ENV{'TMP'} ) {
  $TmpFile = "$ENV{'TMP'}/letter.$$";
} else {
  $TmpFile = "/tmp/letter.$$";
}

open( DECODE, "|mmencode -u $switch > $TmpFile" ) 
  || die "Can't run mmencode writing to $TmpFile";

  while( <> ) {
    print DECODE;
  }
close( DECODE );

open( DECODED, $TmpFile ) || die "Can't open just decoded file $TmpFile";
  while( <DECODED> ) {
    print;
  }
close( DECODED );

unlink( $TmpFile );
