#!/usr/bin/env perl
#
# Copyright 1999-2000 Igor Chudov
#
# This file is part of STUMP.
# 
# STUMP is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# STUMP is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with STUMP.  If not, see <https://www.gnu.org/licenses/>.

$MNG_ROOT = $ENV{'MNG_ROOT'} || die "Root dir for moderation not specified";

require "$MNG_ROOT/bin/robomod.pl";

###################################################################### checkAck
# checks if poster needs ack
sub checkAck {

  $needAck = ! &nameIsInList( $From, "noack.list" );

}


######################################################################
# Getting data
sub readMessage {

  $IsBody = 0;
  
  while( <> ) {
    $Body .= $_;

    chop;
  
    if( /^$/ ) {
      $IsBody = 1;
    }
  
    if( !$IsBody ) {
  
      if( /^Newsgroups: / ) {
        $Newsgroups = $_;
        $Newsgroups =~ s/^Newsgroups: //i;
      } elsif( /^Subject: / ) {
        $Subject = $_;
      } elsif( /^From: / ) {
        $From = $_;
      } elsif( /^Path: / ) {
        $Path = $_;
      } elsif( /^Keywords: / ) {
        $Keywords = $_;
      } elsif( /^Summary: / ) {
        $Summary = $_;
      } elsif( /^Message-ID: / ) {
        $Message_ID = $_;
      }
  
    }
  }

  close( TMPFILE );
}

######################################################################
# read the thing
&readMessage();

######################################################################
# process acks
&checkAck;

if( $needAck ) {
  exit 0;
} else {
  exit 1;
}
