#!/bin/sh
#
# Copyright 1999-2000 Igor Chudov
# Copyright 2020 Tristan Miller
#
# This file is part of STUMP.
# 
# STUMP is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# STUMP is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with STUMP.  If not, see <https://www.gnu.org/licenses/>.

NEWSBIN=/var/lib/newsbin; export NEWSBIN
shift
DATE_STAMP="$(date +%y%m%d%H%M%S)"

TMPFILE="$TMP"/pa."$DATE_STAMP".$$

if [ "$PGP" = "none" ]; then
  PMAPP_PROG=cat
else
  PMAPP_PROG="$PMAPP $NEWSGROUP"
fi

echo Action: processApproved 1>&2

cat > "$TMPFILE"

save() { 

  ( 
    cat "$TMPFILE"
  ) | procmail -f- "$MNG_ROOT"/etc/procmail/save-approved
}

post() {
  FAILED="$TMP"/failed.$$
  (
    echo Path: "$PATH_SUFFIX"

    grep ': ' < "$MNG_ROOT"/etc/added-headers
    # I do grep above because a lot of users inserts empty
    # lines in the added headers.

    echo Date: "$(date "+%a, %e %b %Y %H:%M:%S CST")"
    formail -f -a "Newsgroups: $NEWSGROUP"		\
	    -I Path:					\
            -I X-Moderate-For:                          \
            -I Return-Path:                             \
            -I X-Mailer:                                \
	    -I "Date:"                                  \
            -I "X-400-Received:"                        \
	    -I Received: -I "From " 			\
	    -a "Approved: $PMUSER_APPROVAL"		\
            -I Lines:                                   \
            -I Cc:                                      \
	    -I To: -I Status:                           \
	    < "$TMPFILE"

    if [ -f "$MNG_ROOT"/etc/added-footer ] ; then
      cat "$MNG_ROOT"/etc/added-footer
    fi

  )                                                     \
    | $PMAPP_PROG					\
    | tee "$FAILED"                                     \
    | $RNEWS
  if [ "$?" = "0" ] ; then
    /bin/rm "$FAILED"
  else
    echo IHAVE failed. Look at "$FAILED". 1>&2
  fi
}

PMUSER="$PMUSER_APPROVAL"; export PMUSER
save
post

if needAck < "$TMPFILE"; then
  modack.approved "$TMPFILE"
fi

rm "$TMPFILE"
