#!/bin/sh
#
# Copyright 1999-2000 Igor Chudov
# Copyright 2020 Tristan Miller
#
# This file is part of STUMP.
# 
# STUMP is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# STUMP is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with STUMP.  If not, see <https://www.gnu.org/licenses/>.
#
# This script takes a raw article that is already rejected, creates a 
# reply message, signs it with PGP and sends back to the author.
#

# echo $0 invoked with arguments $@ 1>&2

MESSAGE="$TMP"/rejected.$$

shift; REASON="$1"; export REASON; shift 
#EXPLANATION="$@"; export EXPLANATION

echo Action: processRejected, reason="$REASON" 1>&2

cat  > "$MESSAGE"

save() { 
  procmail -p -f- "$MNG_ROOT"/etc/procmail/save-rejected < "$MESSAGE"
}

reply() {

  (
    formail -rt -I "Reply-To: $BOARD" 	    \
            -I "Errors-To: $MUNGED_ADDRESS" \
	    < "$MESSAGE"
    (
      echo "$EXPLANATION"
      echo

      if [ "x$REASON" != "xcustom" ] ; then
	cat "$MNG_ROOT"/etc/messages/"$REASON"
      fi

      echo ""
      echo ============================================ Full text of your message follows
      sed 's/^/> /' < "$MESSAGE"
    ) | stump-pgp -staf -z "$PMPASSWORD" 	\
            -u "$PMUSER_APPROVAL" +clearsig=on  2>/dev/null \
  ) | sendmail -t -f "$MUNGED_ADDRESS"
}

save
if [ "x$REASON" != "xignore" ] ; then
  reply "$1"
fi
rm "$MESSAGE"
