#!/usr/bin/env perl
#
# Copyright 1999-2000 Igor Chudov
#
# This file is part of STUMP.
# 
# STUMP is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# STUMP is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with STUMP.  If not, see <https://www.gnu.org/licenses/>.
#
# Preapproves the person and gets his/her message posted via processApproved
#

# get the directory where robomod is residing
$MNG_ROOT = $ENV{'MNG_ROOT'} || die "Root dir for moderation not specified";

# common library
require "$MNG_ROOT/bin/robomod.pl";

$GoodGuys = "$MNG_ROOT/data/good.guys.list";

$Argv = join( ' ', @ARGV );


open( PROCESS_APPROVED, "|processApproved $Argv" );

while( <STDIN> ) {
  $From = $_ if( /^From: / );

  print PROCESS_APPROVED;

  chop;
  last if( /^$/ );
}

while( <STDIN> ) { # Body
  print PROCESS_APPROVED;
}

close PROCESS_APPROVED;

$From =~ s/^From: //g;
if( $From =~ m/([\w-\.]*)\@([\w-\.]+)/ ) {
  $From = "$1\@$2";
} else {
  print STDERR "From line `$From' is incorrect\n";
  exit 0;
}

if( !&nameIsInList( $From, "good.guys.list" ) ) { # need to preapprove
  &logAction( "Action: processPreapproved $From\n" );
  open( GOOD_GUYS, ">>$GoodGuys" );
    print GOOD_GUYS "$From\n";
  close( GOOD_GUYS );
} else {
  print STDERR "$From already preapproved\n";
}
