#!/bin/sh
#
# Copyright 1999-2000 Igor Chudov
#
# This file is part of STUMP.
# 
# STUMP is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# STUMP is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with STUMP.  If not, see <https://www.gnu.org/licenses/>.

(
  formail -r -I "Subject: $NEWSGROUP Approval PGP Key"	\
	  -I "Reply-To: devnull@algebra.com"		\
	  -I "Errors-To: devnull@algebra.com"

  cat << _EOB_
Hello,

Thank you for requesting PGP Public Key used to sign submissions to
soc.culture.russian.moderated newsgroup. Please use PGP Moose scripts
to verify integrity of robomod's signatures on your news articles and
report any articles that fail verification to scrm-admin@algebra.com.

Thanks,

	- Your Friendly $NEWSGROUP Robomoderator.

_EOB_
  cat "$MNG_ROOT"/approval.key.txt
) | /usr/sbin/sendmail -t
