#!/bin/sh
#
# Copyright 1999-2000 Igor Chudov
# Copyright 2020 Tristan Miller
#
# This file is part of STUMP.
# 
# STUMP is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# STUMP is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with STUMP.  If not, see <https://www.gnu.org/licenses/>.

if [ "$PGP" = "none" ] ; then
  cat
else 
  if [ "x$PGP" = "x" ] ; then
    if command -v pgp > /dev/null 2>&1; then
      pgp "$@"
    else
      cat "$@"
      echo used cat because pgp was not found 1>&2
    fi
  else
    if [ -x "$PGP" ] ; then
      "$PGP" "$@"
    else
      echo Please define variable PGP in your admin/etc/modenv file 1>&2
      pgp "$@"
    fi
  fi
fi
