#!/bin/sh
#
# Copyright 1999-2000 Igor Chudov
# Copyright 2020 Tristan Miller
#
# This file is part of STUMP.
# 
# STUMP is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# STUMP is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with STUMP.  If not, see <https://www.gnu.org/licenses/>.

NAME="$1"

TMPFILE="$TMP"/vrfy.$$

cat > "$TMPFILE"

if grep -e "^$BEGIN_PGP_SIGNED_MESSAGE" < "$TMPFILE" >/dev/null; then
  SIGNED="YES"
else
  SIGNED="NO"
fi

if [ "$SIGNED" = "NO" ] ; then 
  if [ "x$NAME" != "x" ] ; then
    echo "No valid sig!" 1>&2
    rm "$TMPFILE"
    exit 1
  else 
    rm "$TMPFILE"
    exit 0
  fi
fi

#
# this we do under assumption that message IS signed
#

GOODSIG="Good signature from user \""

DoPGP() {
  stump-pgp -f +batchmode=on +pubring="$MNG_ROOT"/data/pubring.pgp < "$TMPFILE" 2>&1 > /dev/null
}

USERID="$(DoPGP | grep -e "^$GOODSIG" | sed "s/^$GOODSIG//" | sed 's/"\.$//')"

rm "$TMPFILE"

echo USERID = "$USERID" 1>&2

if [ "x$NAME" != "x" ]; then
  if [ "$USERID" = "$NAME" ] ; then
    exit 0
  else
    exit 1
  fi
else
  if [ "x$USERID" = "x" ]; then # bad sig!
    exit 1;
  fi

  echo "$USERID"
  exit 0
fi
